# Generated by Django 4.1.7 on 2023-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_pub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
