# Generated by Django 4.1.7 on 2023-04-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_pub', '0002_story_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='', max_length=100)),
                ('image_de_garde', models.ImageField(default='', null=True, upload_to='pub_images')),
            ],
        ),
    ]
