# Generated by Django 4.1.7 on 2023-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_mus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
