# Generated by Django 4.1.7 on 2023-04-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_mus', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
