# Generated by Django 4.1.7 on 2023-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_student_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='', null=True, upload_to='profile_student_image'),
        ),
    ]
