# Generated by Django 4.1.7 on 2023-04-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Filieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abre', models.CharField(blank=True, default='', max_length=5)),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.levels')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
