# Generated by Django 4.1.7 on 2023-04-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_levels_title_filieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon_title', models.ImageField(upload_to='modules_icon')),
                ('filiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.filieres')),
            ],
        ),
    ]
