# Generated by Django 4.1.7 on 2023-04-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('old_prix', models.CharField(max_length=100, unique=True)),
                ('new_prix', models.CharField(max_length=100, unique=True)),
                ('Module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.CharField(max_length=100, unique=True)),
                ('video_url', models.CharField(max_length=100, unique=True)),
                ('tutorial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='levels.tutorial')),
            ],
        ),
    ]
