# Generated by Django 4.1.7 on 2023-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_tutorial_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='is_free',
            field=models.BooleanField(null=True),
        ),
    ]
