# Generated by Django 4.1.7 on 2023-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapha', '0003_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Cours',
            field=models.ManyToManyField(to='mustapha.cours'),
        ),
    ]
