# Generated by Django 4.1.7 on 2023-04-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapha', '0006_fillier_niveau_remove_person_cours_delete_snippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='abrev',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
