# Generated by Django 4.1.7 on 2023-04-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mustapha', '0007_niveau_abrev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillier',
            options={},
        ),
        migrations.CreateModel(
            name='matier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('fillier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mustapha.fillier')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
