# Generated by Django 4.1.7 on 2023-04-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mustapha', '0008_alter_fillier_options_matier'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='matier',
            options={},
        ),
        migrations.CreateModel(
            name='cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('video', models.CharField(blank=True, default='', max_length=100)),
                ('pdf', models.CharField(blank=True, default='', max_length=100)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mustapha.chapitre')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mustapha.matier'),
        ),
    ]
